name: Publish Obsidian Vault

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download Kiln
        run: |
          curl -L \
            -o kiln \
            https://github.com/otaleghani/kiln/releases/latest/download/kiln_linux_amd64
          chmod +x kiln

      - name: Generate site
        run: |
          ./kiln generate \
            --input ./GI \
            --output ./softeng
         
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./softeng

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
